app/back-end/src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: CarRepository::class)]
#[ORM\Table(name:"car")]
class Car
{
    #[ORM\Id]
    #[ORM\Column(length:17)]
    private ?string $car_vin;

    #[ORM\Column(length:32)]
    private ?string $car_make;

    #[ORM\Column(length:32)]
    private ?string $car_model;

    #[ORM\Column]
    private ?\DateTimeImmutable $car_date_of_issue;

    #[ORM\Column(length:8)]
    private ?string $car_state_number;

    #[ORM\Column(length:32)]
    private ?string $cls_title;

    #[ORM\Column]
    private ?int $stn_id;

    #[ORM\Column(length:64)]
    private ?string $car_body_type;

    #[ORM\Column(length:32)]
    private ?string $car_color;

    #[ORM\Column(name:"car_status", columnDefinition:" INT check (car_status between 0 and 3)")]
    private ?int $car_status;

    #[ORM\Column(length:16)]
    private ?string $car_gearbox_type;

    #[ORM\Column(length:128)]
    private ?string $car_img;

    #[ORM\OneToMany(targetEntity:Booking::class, mappedBy:"car")]
    private ?Collection $bookings;

    #[ORM\ManyToOne(targetEntity:StationService::class, inversedBy:"cars")]
    #[ORM\JoinColumn(name:"stn_id", referencedColumnName:"stn_id")]
    private ?StationService $station_service;

    #[ORM\ManyToOne(targetEntity:CarClass::class, inversedBy:"cars")]
    #[ORM\JoinColumn(name:"cls_title", referencedColumnName:"cls_title")]
    private ?CarClass $car_class;

    #[ORM\ManyToMany(targetEntity:AddService::class, mappedBy:"cars")]
    private ?Collection $add_services;

    public function __construct()
    {
        $this->bookings = new ArrayCollection();
        $this->add_services = new ArrayCollection();
    }

    public function getId(): string
    {
        return $this->car_vin;
    }

    public function getCarVin(): ?string
    {
        return $this->car_vin;
    }

    public function setCarVin(string $car_vin): static
    {
        $this->car_vin = $car_vin;

        return $this;
    }

    public function getCarMake(): ?string
    {
        return $this->car_make;
    }

    public function setCarMake(string $car_make): static
    {
        $this->car_make = $car_make;

        return $this;
    }

    public function getCarModel(): ?string
    {
        return $this->car_model;
    }

    public function setCarModel(string $car_model): static
    {
        $this->car_model = $car_model;

        return $this;
    }

    public function getCarDateOfIssue(): ?\DateTimeImmutable
    {
        return $this->car_date_of_issue;
    }

    public function setCarDateOfIssue(\DateTimeImmutable $car_date_of_issue): static
    {
        $this->car_date_of_issue = $car_date_of_issue;

        return $this;
    }

    public function getCarStateNumber(): ?string
    {
        return $this->car_state_number;
    }

    public function setCarStateNumber(string $car_state_number): static
    {
        $this->car_state_number = $car_state_number;

        return $this;
    }

    public function getClsTitle(): ?string
    {
        return $this->cls_title;
    }

    public function setClsTitle(string $cls_title): static
    {
        $this->cls_title = $cls_title;

        return $this;
    }

    public function getStnId(): ?int
    {
        return $this->stn_id;
    }

    public function setStnId(int $stn_id): static
    {
        $this->stn_id = $stn_id;

        return $this;
    }

    public function getCarBodyType(): ?string
    {
        return $this->car_body_type;
    }

    public function setCarBodyType(string $car_body_type): static
    {
        $this->car_body_type = $car_body_type;

        return $this;
    }

    public function getCarColor(): ?string
    {
        return $this->car_color;
    }

    public function setCarColor(string $car_color): static
    {
        $this->car_color = $car_color;

        return $this;
    }

    public function getCarStatus(): ?int
    {
        return $this->car_status;
    }

    public function setCarStatus(int $car_status): static
    {
        $this->car_status = $car_status;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): static
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setCar($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): static
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getCar() === $this) {
                $booking->setCar(null);
            }
        }

        return $this;
    }

    public function getStationService(): ?StationService
    {
        return $this->station_service;
    }

    public function setStationService(?StationService $station_service): static
    {
        $this->station_service = $station_service;

        return $this;
    }

    public function getCarClass(): ?CarClass
    {
        return $this->car_class;
    }

    public function setCarClass(?CarClass $car_class): static
    {
        $this->car_class = $car_class;

        return $this;
    }

    /**
     * @return Collection<int, AddService>
     */
    public function getAddServices(): Collection
    {
        return $this->add_services;
    }

    public function addAddService(AddService $addService): static
    {
        if (!$this->add_services->contains($addService)) {
            $this->add_services->add($addService);
            $addService->addCar($this);
        }

        return $this;
    }

    public function removeAddService(AddService $addService): static
    {
        if ($this->add_services->removeElement($addService)) {
            $addService->removeCar($this);
        }

        return $this;
    }

    public function getCarImg(): ?string
    {
        return $this->car_img;
    }

    public function setCarImg(string $car_img): static
    {
        $this->car_img = $car_img;

        return $this;
    }

    public function getCarGearboxType(): ?string
    {
        return $this->car_gearbox_type;
    }

    public function setCarGearboxType(string $car_gearbox_type): static
    {
        $this->car_gearbox_type = $car_gearbox_type;

        return $this;
    }
}

app/back-end/src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\AddService;
use App\Entity\Car;
use App\Entity\CarClass;
use App\Entity\StationService;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('car_vin')
            ->add('car_make')
            ->add('car_model')
            ->add('car_date_of_issue', null, [
                'widget' => 'single_text',
            ])
            ->add('car_state_number')
            ->add('cls_title')
            ->add('stn_id')
            ->add('car_body_type')
            ->add('car_color')
            ->add('car_status')
            ->add('car_gearbox_type')
            ->add('car_img')
            ->add('station_service', EntityType::class, [
                'class' => StationService::class,
                'choice_label' => 'id',
            ])
            ->add('car_class', EntityType::class, [
                'class' => CarClass::class,
                'choice_label' => 'id',
            ])
            ->add('add_services', EntityType::class, [
                'class' => AddService::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

app/back-end/src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\AddService;
use App\Entity\Car;
use App\Entity\CarClass;
use App\Entity\StationService;
use App\Repository\CarRepository;
use App\Service\CarsService;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Test\Constraint\ResponseFormatSame;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/car')]
class CarController extends AbstractController
{
    public function __construct(
        private CarsService $carsService,
    ) {
    }

    #[Route('/', methods: ['GET'])]
    public function index(CarRepository $carRepository, Request $request): Response
    {
        $page = $request->get('page', 1);
        return $this->json($this->carsService->getCars($page));
    }

    #[Route('/for_client', methods: ['GET'])]
    public function cars(CarRepository $carRepository): Response
    {
        /*
        0 - Удалена из каталога
        1 - В аренде
        2 - Находится в пункте выдачи
        3 - На ремонте
        */
        $cars = $carRepository->findAll();
        $carsResponse = [];
        foreach ($cars as $car) {
            if ($car->getCarStatus() == 2) {
                $addServicesArr = [];
                $addServices = $car->getAddServices();
                foreach ($addServices as $addService) {
                    $addServicesArr[] = $addService->getSrvType();
                }
                $cost =  $car->getCarClass()->getClsCoefCost()*2000;
                foreach ($addServices as $addService) {
                    $cost += $addService->getSrvCost();
                }
                
                $carsResponse[] = [
                    "id" => $car->getCarVin(),
                    "mark" => $car->getCarMake(),
                    "model" => $car->getCarModel(),
                    "date" => $car->getCarDateOfIssue()->format('Y-m-d'),
                    "state_number" => $car->getCarStateNumber(),
                    "cls_title" => $car->getCarClass()->getClsTitle(),
                    "image" => $car->getCarImg(),
                    "station_service" => $car->getStationService()->getStnAddress(),
                    "body_type" => $car->getCarBodyType(),
                    "color" => $car->getCarColor(),
                    "status" => $car->getCarStatus(),
                    "gearbox" => $car->getCarGearboxType(),
                    "add_services" => $addServicesArr,
                    "cost" => $cost,
                ];
            }
        }
        return $this->json($carsResponse);
    }

    #[Route('/new', methods: ["POST"])]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $request = $request->toArray();
        $car = new Car();
        $car->setCarVin($request['id'])
            ->setCarMake($request['mark'])
            ->setCarModel($request['model'])
            ->setCarDateOfIssue(DateTimeImmutable::createFromFormat('Y-m-d', $request['date']))
            ->setCarClass($manager->getRepository(CarClass::class)->findBy(['cls_title' => $request['cls_title']])[0])
            ->setCarImg($request['image'])
            ->setCarStateNumber($request['state_number'])
            ->setCarGearboxType($request['gearbox'])
            ->setCarColor($request['color'])
            ->setCarStatus($request['status'])
            ->setStationService($manager->getRepository(StationService::class)->findBy(['stn_address' => $request['station_service']])[0])
            ->setCarBodyType($request['body_type']);
        foreach ($request['add_services'] as $ads) {
            $addService = $manager->getRepository(AddService::class)->findOneBy(['srv_type' => $ads]);
            $car->addAddService($addService);
        }
        $manager->persist($car);
        $manager->flush();
        return $this->json($request);
    }

    #[Route('/{car_vin}/edit', methods: ['PUT', 'PATCH'])]
    public function edit(Request $request, EntityManagerInterface $manager, string $car_vin): Response
    {
        $request = $request->toArray();
        $car = $manager->getRepository(Car::class)->findBy(['car_vin' => $car_vin])[0];
        if ($car) {
            $car->setCarMake($request['mark'])
                ->setCarModel($request['model'])
                ->setCarDateOfIssue(DateTimeImmutable::createFromFormat('Y-m-d', $request['date']))
                ->setCarClass($manager->getRepository(CarClass::class)->findBy(['cls_title' => $request['cls_title']])[0])
                ->setCarImg($request['image'])
                ->setCarStateNumber($request['state_number'])
                ->setCarGearboxType($request['gearbox'])
                ->setCarColor($request['color'])
                ->setCarStatus($request['status'])
                ->setStationService($manager->getRepository(StationService::class)->findBy(['stn_address' => $request['station_service']])[0])
                ->setCarBodyType($request['body_type']);
            foreach ($request['add_services'] as $ads) {
                $addService = $manager->getRepository(AddService::class)->findOneBy(['srv_type' => $ads]);
                $car->addAddService($addService);
            }
            $manager->persist($car);
            $manager->flush();
            return $this->json($request);
        }
        return $this->json(['error' => 'Такого автомобиля не существует']);
    }

    #[Route('/{car_vin}/delete', methods: ['DELETE'])]
    public function delete(EntityManagerInterface $manager, string $car_vin)
    {
        $car = $manager->getRepository(Car::class)->findBy(['car_vin' => $car_vin])[0];
        if ($car) {
            $manager->remove($car);
            $manager->flush();
            return $this->json(['ok' => "Автомобиль удален"]);
        }
        return $this->json(['error' => 'Такого автомобиля не существует']);
    }

    #[Route('/upload', methods: ['POST'])]
    public function upload(Request $request)
    {
        $file = $request->files->get('demo')[0];
        if ($file) {
            $filename = $file->getClientOriginalName();
            $arrFilename = explode('.', $filename);
            $randomIndex = (string)random_int(1, 1000);
            $newFilename = hash('sha256', $filename . $randomIndex) . '.' . $arrFilename[count($arrFilename)-1];
            $file->move($this->getParameter('upload_directory'), $newFilename);
            return $this->json(["path" => "/img/cars/" . $newFilename]);
        }
        return $this->json(["er" => $file]);
    }

    #[Route('/report', methods: ['GET'])]
    public function report(EntityManagerInterface $manager): Response
    {
        $cars = $manager->getRepository(Car::class)->report();
        return $this->json($cars);
    }
}

app/back-end/templates/car/_delete_form.html.twig
<form method="post" action="{{ path('app_car_delete', {'car_vin': car.car_vin}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.car_vin) }}">
    <button class="btn">Delete</button>
</form>

app/back-end/templates/car/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/back-end/templates/car/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Car{% endblock %}

{% block body %}
    <h1>Edit Car</h1>

    {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_car_index') }}">back to list</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}

app/back-end/templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car index{% endblock %}

{% block body %}
    <h1>Car index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Car_vin</th>
                <th>Car_make</th>
                <th>Car_model</th>
                <th>Car_date_of_issue</th>
                <th>Car_state_number</th>
                <th>Cls_title</th>
                <th>Stn_id</th>
                <th>Car_body_type</th>
                <th>Car_color</th>
                <th>Car_status</th>
                <th>Car_gearbox_type</th>
                <th>Car_img</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for car in cars %}
            <tr>
                <td>{{ car.carVin }}</td>
                <td>{{ car.carMake }}</td>
                <td>{{ car.carModel }}</td>
                <td>{{ car.carDateOfIssue ? car.carDateOfIssue|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ car.carStateNumber }}</td>
                <td>{{ car.clsTitle }}</td>
                <td>{{ car.stnId }}</td>
                <td>{{ car.carBodyType }}</td>
                <td>{{ car.carColor }}</td>
                <td>{{ car.carStatus }}</td>
                <td>{{ car.carGearboxType }}</td>
                <td>{{ car.carImg }}</td>
                <td>
                    <a href="{{ path('app_car_show', {'car_vin': car.car_vin}) }}">show</a>
                    <a href="{{ path('app_car_edit', {'car_vin': car.car_vin}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_car_new') }}">Create new</a>
{% endblock %}

app/back-end/templates/car/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Car{% endblock %}

{% block body %}
    <h1>Create new Car</h1>

    {{ include('car/_form.html.twig') }}

    <a href="{{ path('app_car_index') }}">back to list</a>
{% endblock %}

app/back-end/templates/car/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car{% endblock %}

{% block body %}
    <h1>Car</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Car_vin</th>
                <td>{{ car.carVin }}</td>
            </tr>
            <tr>
                <th>Car_make</th>
                <td>{{ car.carMake }}</td>
            </tr>
            <tr>
                <th>Car_model</th>
                <td>{{ car.carModel }}</td>
            </tr>
            <tr>
                <th>Car_date_of_issue</th>
                <td>{{ car.carDateOfIssue ? car.carDateOfIssue|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Car_state_number</th>
                <td>{{ car.carStateNumber }}</td>
            </tr>
            <tr>
                <th>Cls_title</th>
                <td>{{ car.clsTitle }}</td>
            </tr>
            <tr>
                <th>Stn_id</th>
                <td>{{ car.stnId }}</td>
            </tr>
            <tr>
                <th>Car_body_type</th>
                <td>{{ car.carBodyType }}</td>
            </tr>
            <tr>
                <th>Car_color</th>
                <td>{{ car.carColor }}</td>
            </tr>
            <tr>
                <th>Car_status</th>
                <td>{{ car.carStatus }}</td>
            </tr>
            <tr>
                <th>Car_gearbox_type</th>
                <td>{{ car.carGearboxType }}</td>
            </tr>
            <tr>
                <th>Car_img</th>
                <td>{{ car.carImg }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_car_index') }}">back to list</a>

    <a href="{{ path('app_car_edit', {'car_vin': car.car_vin}) }}">edit</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}